# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22381c578fbcb40a5d2664d20a45b33d0fe64777a9df274d800d8e2f187b40c7665741455fc925b929d2e69486f99a6276bf3c597da1483af070089dcfdb3973

test:
  secret_key_base: df7004ecd7ed00319e0b7dc8aab597c221b116c1ff487c4d370cc699123f21debac157acf0e2cbe17a1a56d377208967156f0bbff9660e34907c93e6c286ac15

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
